name: Common Release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  release:
    runs-on: ubuntu-latest

    # Step 1: Checkout the repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Basic GitHub setup
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "sancler@moonshotteam.com"

    # Step 3: Create a GitHub Release
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')  # Only run on tag push
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: "Release notes for version ${{ github.ref_name }}."
        draft: false
        prerelease: false
